spring:
  datasource:
    hikari:
      data-source-properties:
        # Performance optimizations regarding prepared statements and inserts/updates batching
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
    url: jdbc:postgresql://localhost:5438/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      # Performance optimizations inserts/updates batching
      hibernate:
        jdbc:
          batch_size: 10
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: true
  liquibase:
    contexts: test
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false
movie-detail-provider:
    omdb:
      url: https://www.omdbapi.com
springdoc:
  default-produces-media-type: application/json
